In [20]:
import numpy as np 
import pandas as pd 

# To consume Twitter's API
import tweepy
from tweepy import OAuthHandler 


from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [21]:
# keys and tokens from the Twitter Dev Console
consumer_key = 'Sec3MvclRIx2RVlgu9l0SJX6D'
consumer_secret = 'ayoPNWtBm7fWpMBoK6EwRmegu3SW8Rw9mzJkottkv97quPe941'
access_token = '736550752760406018-so5CPJrEbJKb3c3Pq8va3VFr0yk4S0E'
access_token_secret = 'Cgr8tz0h6FTU7kxAjDzpHnjffNTHxWsBytXnu4Ihd1TFb'

In [22]:
class TwitterClient(object): 
    def __init__(self): 
        #Initialization method. 
        try: 
            # create OAuthHandler object 
            auth = OAuthHandler(consumer_key, consumer_secret) 
            # set access token and secret 
            auth.set_access_token(access_token, access_token_secret) 
            # create tweepy API object to fetch tweets 
            # add hyper parameter 'proxy' if executing from behind proxy "proxy='http://172.22.218.218:8085'"
            self.api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
            
        except tweepy.TweepError as e:
            print(f"Error: Tweeter Authentication Failed - \n{str(e)}")

    def get_tweets(self, query, maxTweets = 1000):
        #Function to fetch tweets. 
        # empty list to store parsed tweets 
        tweets = [] 
        sinceId = None
        max_id = -1
        tweetCount = 0
        tweetsPerQry = 100

        while tweetCount < maxTweets:
            try:
                if (max_id <= 0):
                    if (not sinceId):
                        new_tweets = self.api.search(q=query, count=tweetsPerQry)
                    else:
                        new_tweets = self.api.search(q=query, count=tweetsPerQry,
                                                since_id=sinceId)
                else:
                    if (not sinceId):
                        new_tweets = self.api.search(q=query, count=tweetsPerQry,
                                                max_id=str(max_id - 1))
                    else:
                        new_tweets = self.api.search(q=query, count=tweetsPerQry,
                                                max_id=str(max_id - 1),
                                                since_id=sinceId)
                if not new_tweets:
                    print("No more tweets found")
                    break

                for tweet in new_tweets:
                    parsed_tweet = {} 
                    parsed_tweet['tweets'] = tweet.text 

                    # appending parsed tweet to tweets list 
                    if tweet.retweet_count > 0: 
                        # if tweet has retweets, ensure that it is appended only once 
                        if parsed_tweet not in tweets: 
                            tweets.append(parsed_tweet) 
                    else: 
                        tweets.append(parsed_tweet) 
                        
                tweetCount += len(new_tweets)
                print("Downloaded {0} tweets".format(tweetCount))
                max_id = new_tweets[-1].id

            except tweepy.TweepError as e:
                # Just exit if any error
                print("Tweepy error : " + str(e))
                break
        
        return pd.DataFrame(tweets)

## (A). Mining Latest topic of Elon Musk from twitter

In [23]:
twitter_client = TwitterClient()

# calling function to get tweets
tweets_df = twitter_client.get_tweets('ElonMusk', maxTweets=100000)
print(f'tweets_df Shape - {tweets_df.shape}')
tweets_df.head(10)

Downloaded 100 tweets
Downloaded 200 tweets
Downloaded 300 tweets
Downloaded 400 tweets
Downloaded 500 tweets
Downloaded 600 tweets
Downloaded 700 tweets
Downloaded 800 tweets
Downloaded 900 tweets
Downloaded 1000 tweets
Downloaded 1100 tweets
Downloaded 1200 tweets
Downloaded 1300 tweets
Downloaded 1400 tweets
Downloaded 1500 tweets
Downloaded 1600 tweets
Downloaded 1700 tweets
Downloaded 1800 tweets
Downloaded 1900 tweets
Downloaded 2000 tweets
Downloaded 2100 tweets
Downloaded 2200 tweets
Downloaded 2300 tweets
Downloaded 2400 tweets
Downloaded 2500 tweets
Downloaded 2600 tweets
Downloaded 2700 tweets
Downloaded 2800 tweets
Downloaded 2900 tweets
Downloaded 3000 tweets
Downloaded 3100 tweets
Downloaded 3200 tweets
Downloaded 3300 tweets
Downloaded 3400 tweets
Downloaded 3500 tweets
Downloaded 3600 tweets
Downloaded 3700 tweets
Downloaded 3800 tweets
Downloaded 3900 tweets
Downloaded 4000 tweets
Downloaded 4100 tweets
Downloaded 4200 tweets
Downloaded 4300 tweets
Downloaded 4400 tweets
Downloaded 4500 tweets
Downloaded 4600 tweets
Downloaded 4700 tweets
Downloaded 4800 tweets
Downloaded 4900 tweets
Downloaded 4991 tweets
Downloaded 5091 tweets
Downloaded 5181 tweets
Downloaded 5281 tweets
Downloaded 5375 tweets
Downloaded 5475 tweets
Downloaded 5565 tweets
Downloaded 5665 tweets
Downloaded 5765 tweets
Downloaded 5860 tweets
Downloaded 5939 tweets
Downloaded 6027 tweets
Downloaded 6127 tweets
Downloaded 6227 tweets
Downloaded 6327 tweets
Downloaded 6427 tweets
Downloaded 6527 tweets
Downloaded 6627 tweets
Downloaded 6727 tweets
Downloaded 6815 tweets
Downloaded 6892 tweets
Downloaded 6950 tweets
Downloaded 7022 tweets
Downloaded 7092 tweets
Downloaded 7171 tweets
Downloaded 7268 tweets
Downloaded 7368 tweets
Downloaded 7468 tweets
Downloaded 7568 tweets
Downloaded 7668 tweets
Downloaded 7768 tweets
Downloaded 7868 tweets
Downloaded 7968 tweets
Downloaded 8066 tweets
Downloaded 8164 tweets
Downloaded 8264 tweets
Downloaded 8361 tweets
Downloaded 8453 tweets
Downloaded 8553 tweets
Downloaded 8653 tweets
Downloaded 8753 tweets
Downloaded 8853 tweets
Downloaded 8953 tweets
Downloaded 9053 tweets
Downloaded 9153 tweets
Downloaded 9253 tweets
Downloaded 9353 tweets
Downloaded 9453 tweets
Downloaded 9537 tweets
Downloaded 9613 tweets
Downloaded 9676 tweets
Downloaded 9754 tweets
Downloaded 9823 tweets
Downloaded 9880 tweets
Downloaded 9940 tweets
Downloaded 10006 tweets
Downloaded 10064 tweets
Downloaded 10109 tweets
Downloaded 10167 tweets
Downloaded 10246 tweets
Downloaded 10299 tweets
Downloaded 10363 tweets
Downloaded 10440 tweets
Downloaded 10520 tweets
Downloaded 10585 tweets
Downloaded 10652 tweets
Downloaded 10720 tweets
Downloaded 10788 tweets
Downloaded 10870 tweets
Downloaded 10970 tweets
Downloaded 11054 tweets
Downloaded 11120 tweets
Downloaded 11187 tweets
Downloaded 11250 tweets
Downloaded 11330 tweets
Downloaded 11411 tweets
Downloaded 11475 tweets
Downloaded 11535 tweets
Downloaded 11604 tweets
Downloaded 11668 tweets
Downloaded 11732 tweets
Downloaded 11788 tweets
Downloaded 11855 tweets
Downloaded 11905 tweets
Downloaded 11972 tweets
Downloaded 12042 tweets
Downloaded 12127 tweets
Downloaded 12185 tweets
Downloaded 12234 tweets
Downloaded 12288 tweets
Downloaded 12352 tweets
Downloaded 12412 tweets
Downloaded 12457 tweets
Downloaded 12498 tweets
Downloaded 12563 tweets
Downloaded 12620 tweets
Downloaded 12666 tweets
Downloaded 12729 tweets
Downloaded 12788 tweets
Downloaded 12838 tweets
Downloaded 12871 tweets
Downloaded 12914 tweets
Downloaded 12945 tweets
Downloaded 12995 tweets
Downloaded 13070 tweets
Downloaded 13116 tweets
Downloaded 13161 tweets
Downloaded 13216 tweets
Downloaded 13262 tweets
Downloaded 13326 tweets
Downloaded 13373 tweets
Downloaded 13411 tweets
Downloaded 13451 tweets
Downloaded 13501 tweets
Downloaded 13551 tweets
Downloaded 13602 tweets
Downloaded 13661 tweets
Downloaded 13693 tweets
Downloaded 13745 tweets
Downloaded 13812 tweets
Downloaded 13900 tweets
Downloaded 13992 tweets
Downloaded 14092 tweets
Downloaded 14190 tweets
Downloaded 14276 tweets
Downloaded 14376 tweets
Downloaded 14472 tweets
Downloaded 14560 tweets
Downloaded 14639 tweets
Downloaded 14722 tweets
Downloaded 14806 tweets

Rate limit reached. Sleeping for: 216

Downloaded 14906 tweets
Downloaded 15006 tweets
Downloaded 15106 tweets
Downloaded 15206 tweets
Downloaded 15306 tweets
Downloaded 15406 tweets
Downloaded 15506 tweets
Downloaded 15606 tweets
Downloaded 15706 tweets
Downloaded 15806 tweets
Downloaded 15906 tweets
Downloaded 16006 tweets
Downloaded 16106 tweets
Downloaded 16206 tweets
Downloaded 16306 tweets
Downloaded 16406 tweets
Downloaded 16506 tweets
Downloaded 16606 tweets
Downloaded 16706 tweets
Downloaded 16806 tweets
Downloaded 16906 tweets
Downloaded 17006 tweets
Downloaded 17106 tweets
Downloaded 17206 tweets
Downloaded 17306 tweets
Downloaded 17406 tweets
Downloaded 17506 tweets
Downloaded 17606 tweets
Downloaded 17706 tweets
Downloaded 17806 tweets
Downloaded 17906 tweets
Downloaded 18006 tweets
Downloaded 18106 tweets
Downloaded 18206 tweets
Downloaded 18306 tweets
Downloaded 18406 tweets
Downloaded 18506 tweets
Downloaded 18605 tweets
Downloaded 18704 tweets
Downloaded 18796 tweets
Downloaded 18886 tweets
Downloaded 18984 tweets
Downloaded 19058 tweets
Downloaded 19158 tweets
Downloaded 19251 tweets
Downloaded 19345 tweets
Downloaded 19445 tweets
Downloaded 19545 tweets
Downloaded 19645 tweets
Downloaded 19745 tweets
Downloaded 19845 tweets
Downloaded 19945 tweets
Downloaded 20045 tweets
Downloaded 20145 tweets
Downloaded 20245 tweets
Downloaded 20345 tweets
Downloaded 20445 tweets
Downloaded 20545 tweets
Downloaded 20645 tweets
Downloaded 20745 tweets
Downloaded 20845 tweets
Downloaded 20945 tweets
Downloaded 21045 tweets
Downloaded 21145 tweets
Downloaded 21245 tweets
Downloaded 21345 tweets
Downloaded 21445 tweets
Downloaded 21545 tweets
Downloaded 21645 tweets
Downloaded 21745 tweets
Downloaded 21845 tweets
Downloaded 21945 tweets
Downloaded 22045 tweets
Downloaded 22145 tweets
Downloaded 22245 tweets
Downloaded 22345 tweets
Downloaded 22445 tweets
Downloaded 22545 tweets
Downloaded 22645 tweets
Downloaded 22745 tweets
Downloaded 22845 tweets
Downloaded 22945 tweets
Downloaded 23045 tweets
Downloaded 23145 tweets
Downloaded 23245 tweets
Downloaded 23345 tweets
Downloaded 23445 tweets
Downloaded 23545 tweets
Downloaded 23645 tweets
Downloaded 23745 tweets
Downloaded 23845 tweets
Downloaded 23945 tweets
Downloaded 24045 tweets
Downloaded 24145 tweets
Downloaded 24245 tweets
Downloaded 24345 tweets
Downloaded 24445 tweets
Downloaded 24545 tweets
Downloaded 24645 tweets
Downloaded 24745 tweets
Downloaded 24845 tweets
Downloaded 24945 tweets
Downloaded 25045 tweets
Downloaded 25145 tweets
Downloaded 25245 tweets
Downloaded 25345 tweets
Downloaded 25445 tweets
Downloaded 25545 tweets
Downloaded 25645 tweets
Downloaded 25745 tweets
Downloaded 25845 tweets
Downloaded 25945 tweets
Downloaded 26045 tweets
Downloaded 26145 tweets
Downloaded 26245 tweets
Downloaded 26345 tweets
Downloaded 26445 tweets
Downloaded 26545 tweets
Downloaded 26645 tweets
Downloaded 26745 tweets
Downloaded 26845 tweets
Downloaded 26945 tweets
Downloaded 27045 tweets
Downloaded 27145 tweets
Downloaded 27245 tweets
Downloaded 27345 tweets
Downloaded 27445 tweets
Downloaded 27545 tweets
Downloaded 27645 tweets
Downloaded 27745 tweets
Downloaded 27845 tweets
Downloaded 27945 tweets
Downloaded 28045 tweets
Downloaded 28145 tweets
Downloaded 28245 tweets
Downloaded 28345 tweets
Downloaded 28445 tweets
Downloaded 28545 tweets
Downloaded 28645 tweets
Downloaded 28745 tweets
Downloaded 28845 tweets
Downloaded 28945 tweets
Downloaded 29045 tweets
Downloaded 29145 tweets
Downloaded 29245 tweets
Downloaded 29345 tweets
Downloaded 29445 tweets
Downloaded 29545 tweets
Downloaded 29645 tweets
Downloaded 29745 tweets
Downloaded 29845 tweets
Downloaded 29945 tweets
Downloaded 30045 tweets
Downloaded 30145 tweets
Downloaded 30245 tweets
Downloaded 30345 tweets
Downloaded 30445 tweets
Downloaded 30545 tweets
Downloaded 30645 tweets
Downloaded 30745 tweets
Downloaded 30845 tweets
Downloaded 30945 tweets
Downloaded 31045 tweets
Downloaded 31145 tweets
Downloaded 31245 tweets
Downloaded 31345 tweets
Downloaded 31445 tweets
Downloaded 31545 tweets
Downloaded 31645 tweets
Downloaded 31745 tweets
Downloaded 31845 tweets
Downloaded 31945 tweets
Downloaded 32045 tweets
Downloaded 32145 tweets
Downloaded 32245 tweets
Downloaded 32345 tweets
Downloaded 32445 tweets
Downloaded 32545 tweets
Downloaded 32645 tweets
Downloaded 32745 tweets

Rate limit reached. Sleeping for: 208

Downloaded 32845 tweets
Downloaded 32945 tweets
Downloaded 33045 tweets
Downloaded 33145 tweets
Downloaded 33245 tweets
Downloaded 33345 tweets
Downloaded 33445 tweets
Tweepy error : Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out.
tweets_df Shape - (25757, 1)

                                              tweets
0  @elonmusk @realfuckingnews @business Ancient c...
1  @elonmusk @rockstardenied @SpaceX Very kind, a...
2               @elonmusk What will happen to Dodge?
3  RT @_0121Dan: Day 8 of tweeting @elonmusk and ...
4  @rockstardenied @elonmusk @SpaceX Download the...
5  @elonmusk I need to buy tesla model x help urg...
6  #ElonMusk: Owning #bitcoin only slightly bette...
7                            @elonmusk Who are they?
8  Congrats Perseverance!!\nHoping to see "mars r...
9  @rockstardenied @elonmusk @SpaceX Download the...

## (B) Sentiment Analysis of Elon Musk Tweets

In [28]:
def fetch_sentiment_using_SIA(text):
    sid = SentimentIntensityAnalyzer()
    polarity_scores = sid.polarity_scores(text)
    return 'neg' if polarity_scores['neg'] > polarity_scores['pos'] else 'pos'

In [29]:
sentiments_using_SIA = tweets_df.tweets.apply(lambda tweet: fetch_sentiment_using_SIA(tweet))
pd.DataFrame(sentiments_using_SIA.value_counts())

     tweets
pos   22725
neg    3032

In [30]:
tweets_df['sentiment'] = sentiments_using_SIA
tweets_df.head()

                                              tweets sentiment
0  @elonmusk @realfuckingnews @business Ancient c...       pos
1  @elonmusk @rockstardenied @SpaceX Very kind, a...       pos
2               @elonmusk What will happen to Dodge?       pos
3  RT @_0121Dan: Day 8 of tweeting @elonmusk and ...       neg
4  @rockstardenied @elonmusk @SpaceX Download the...       pos

In [31]:
df = tweets_df
df.to_csv('Elon Musk.csv')

In [33]:
em = pd.read_csv("Elon Musk.csv")

In [34]:
em.shape

(25757, 3)

In [36]:
em.head(10)

   Unnamed: 0                                             tweets sentiment
0           0  @elonmusk @realfuckingnews @business Ancient c...       pos
1           1  @elonmusk @rockstardenied @SpaceX Very kind, a...       pos
2           2               @elonmusk What will happen to Dodge?       pos
3           3  RT @_0121Dan: Day 8 of tweeting @elonmusk and ...       neg
4           4  @rockstardenied @elonmusk @SpaceX Download the...       pos
5           5  @elonmusk I need to buy tesla model x help urg...       pos
6           6  #ElonMusk: Owning #bitcoin only slightly bette...       pos
7           7                            @elonmusk Who are they?       pos
8           8  Congrats Perseverance!!\nHoping to see "mars r...       pos
9           9  @rockstardenied @elonmusk @SpaceX Download the...       pos

In [37]:
em.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25757 entries, 0 to 25756
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  25757 non-null  int64
 1   tweets      25757 non-null  object
 2   sentiment   25757 non-null  object
dtypes: int64(1), object(2)
memory usage: 603.8+ KB